server:
  port: 8080
spring:
  profiles:
    active: test
    include: ttt
  ##--------------Redis配置-----------------##
# Redis数据库索引（默认为0）
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 82878871
    # 连接超时时间（毫秒）
    timeout: 60000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/project/UserMapper.xml

---
server:
  port: 9991
spring:
  profiles:
    active: test1
    include: ttt1
springlearn: cheshi

---
server:
  port: 9992
spring:
  profiles: test
springlearn: cheshi